CREATE DATABASE QLSVien
GO
use QLSVien
GO
CREATE TABLE KHOA
(
	MAKHOA		VARCHAR(4) NOT NULL,
	TENKHOA		VARCHAR(30) NOT NULL,
	NAMTHANHLAP	INT,
	PRIMARY KEY (MAKHOA)
)

CREATE TABLE SVIEN
(
	TEN	VARCHAR(30) NOT NULL,
	MASV	INT	NOT NULL,
	NAM	INT,
	MAKH	VARCHAR(4) NOT NULL,
	CHECK(NAM >= 1 AND NAM <= 4),
	PRIMARY KEY (MASV),
	CONSTRAINT FK_SVIEN_MAKHOA FOREIGN KEY (MAKH)
		REFERENCES KHOA (MAKHOA)
)

CREATE TABLE MHOC
(
	TENMH	VARCHAR(30) NOT NULL,
	MAMH	VARCHAR(8) NOT NULL,
	TINCHI 	INT,
	MAKH	VARCHAR(4),
	PRIMARY KEY (MAMH),
	CONSTRAINT FK_MHOC_MAKH FOREIGN KEY (MAKH)
		REFERENCES KHOA (MAKHOA)
)

CREATE TABLE DKIEN
(
	MAMH		VARCHAR(8) NOT NULL,
	MAMH_TRUOC	VARCHAR(8) NOT NULL,
	PRIMARY KEY (MAMH,MAMH_TRUOC),
	CONSTRAINT FK_DKIEN_MAMH FOREIGN KEY (MAMH)
		REFERENCES MHOC (MAMH)
)

CREATE TABLE HPHAN
(
	MAHP	INT NOT NULL,
	MAMH	VARCHAR(8) NOT NULL,
	HOCKI	INT,
	NAM	INT,
	GV	VARCHAR(30),
	PRIMARY KEY (MAHP),
	CONSTRAINT FK_HPHAN_MAMH FOREIGN KEY (MAMH)
		REFERENCES MHOC (MAMH)
)

CREATE TABLE KQUA
(
	MASV	INT NOT NULL,
	MAHP	INT NOT NULL,
	DIEM	FLOAT,
	CHECK(DIEM >= 0 AND DIEM <=10),
	PRIMARY KEY (MASV,MAHP),
CONSTRAINT FK_KQUA_MASV FOREIGN KEY (MASV)
		REFERENCES SVIEN (MASV),
	CONSTRAINT FK_KQUA_MAHP FOREIGN KEY (MAHP)
		REFERENCES HPHAN (MAHP)
)
